name: Matrix Demo
on: push
jobs: 

    build:

        strategy: 
            matrix:
                node-version: [12, 14, 16]
                OS: [ubuntu-latest, windows-latest]

        runs-on: ${{ matrix.OS }}

        steps:
            - name: Get Code
              uses: actions/checkout@v3

            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version}}

            - name: Install Depencies
              run: npm ci

            - name: Build Project
              run: npm run build
